### ISSUE TITLE
flash.py generates a no such file exception

### ISSUE THREAD

**Issue by rbucker** [scumjr/yubikeyedup#1]
The environment: alpinelinux 3.3.1 running inside a docker container.

I created my database and was then creating the first user:

```
$./tools/flash.py bob ./yubikeys.sqlite3
Traceback (most recent call last):
  File "./tools/flash.py", line 44, in <module>
    ret = subprocess.call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by scumjr** [comment]
`flash.py` executes `sudo` in order to run `ykpersonalize` with root privileges. I think `sudo` isn't installed on your system. Commit 8cc9723 should fix this error.

**Comment by rbucker** [comment]
clearly you are welcome to close the issue, however, if sudo is a required tool the issue could be reopened as a request to correct the error rather than just fail.

**Comment by scumjr** [comment]
Sorry, I didn't mention that `sudo` isn't a requirement anymore since commit 8cc9723.
